### PR TITLE
add the bounty solution to solve the issue: #2

### PR DESCRIPTION
**Pull request by AaronZgl**
solve #2

### CODE REVIEW

**Comment by deprecated1234** [comment]
https://hackerlink.io/bounty/14
Issue: Time weighted distribution algorithm.

**Comment by Skyge** [comment]
Hey, glad to see your solution, but can you offer a simply doc to explain this contract, or just write a simple test case, so I can understand it better.

**Comment by tturbulence** [comment]
> Hey, glad to see your solution, but can you offer a simply doc to explain this contract, or just write a simple test case, so I can understand it better.

Hello, we're from xDeFi team ( 2020 Dorahacks Hackathon).

The solution is for:

1. Given a certain pre-defined amount of total reward, we can define a stream: type is Stream, and depositAmount is the pre-charged amount of reward for the stream, gradually released from startBlock till stopBlock
2. function normalCDF is an auxiliary function. If the reward stream is released proportional to a standard normal distribution, its integration function, the cumulative distribution function of this random normal distribution will be callled later.
3. Reward will be distributed between startBlock and stopBlock after this stream initiated.
4. At any block height, Recipient can withdraw some reward, or check how much reward he can withdraw at most. The maximum amount withdrawable from this stream for Recipient won't exceed normalCDF(X), where X is mapped from a linear mapping that: X is mapped from blockheight, -3 is mapped from startBlock, +3 is mapped from stopBlock

**Comment by Skyge** [comment]
Thanks for your explanation, but does it satisfy  the requirement `for the same amount of LP staked, a longer staking period will receive more rewards per second.`

**Comment by annamc93** [comment]
Hey

**Pull request closed without merging**
