### PR TITLE
solve the issue 2: Time weighted distribution algorithm.

### PR DESCRIPTION
**Pull request by AaronZgl**
#2 
The solution is an arithmetic sequence model:
An = A1+(n-1)d
Sn = (A1+An)*n/2

An is the reward in n'th seconds (An is the sn in issue)
Sn is the total reward
A1 is the first second reward
d is the increment per second
n is the total seconds

you should specify: 
- Sn: total reward amount
- n: startRewardBlock - stopRewardBlock
- times: the times the last number more than the first number (An/A1)

we can calculate A1 and d from above
An is the reward amount per second, A1 < A2 < A3 ... < An | A1 + A2 + ... + An = Sn

### CODE REVIEW

**Comment by Skyge** [comment]
Hey, I just found you made a new PR, so how about the previous one? #3 Can I close it and now focus on this one?

**Comment by AaronZgl** [comment]
> Hey, I just found you made a new PR, so how about the previous one? #3 Can I close it and now focus on this one?

Yes, the previous one's result is `s1 < s2 < s3 < ... < sm > sm+1 > sm+2 > ... > sn` , it may not satisfy the requirement. this one's result is `s1 < s2 < s3 < ... < sn`. （the S is the reward per second, not the sum of first n seconds.）
I'm very sorry that I quoted the wrong branch, resulting in 11 files changed in this pr. You can  just focus on the `contracts/Bounty.sol` and delete others.

**Comment by Skyge** [comment]
@AaronZgl Hey, sorry to reply so late, I wrote a test case to test your contract, but it did not work as expected.
In order to deploy the contract, I need to provide the following parameters:
```
_rewardToken   <<<--- a standard ERC20
_stakeToken     <<<--- a standard ERC20, just use the same token with `_rewardToken`
_rewardAmount     <<<---  12000 * 10 ** 18
_rewardStartBlock <<<--- current block number
_rewardStopBlock <<<--- current block number + 6646
```
I assume that 12,000 token will be distributed per day(suppose one day has 6646 blocks), then I just used two accounts to `stake`, `user1` staked at the beginning with 2,000 token, after 100 blocks, `user2` also staked  with 2,000 token, then `user1` exited staking to get reward, and next `user2` also exited to get reward, I found that the rewards of the two users are almost equal, so I am not sure wether I tested wrongly. 
Cause in the description of this bounty: [for the same amount of LP staked, a longer staking period will receive more rewards per second.](https://github.com/dforce-network/staking/issues/2).
What do you think about this PR? @joyious

**Comment by joyious** [comment]
Hey @AaronZgl, thanks for working on the bounty, and sorry for the late reply. Here are some of my thoughts:

- We prefer to keep the original structure of the staking contract in order to be compatible with the frontend and other systems, which means you may have to keep the same public interfaces, such as `stake()`, `withdraw()`, `exit()`, `getReward()` etc.

- As @Skyge mentioned earlier, it would be better to submit some tests as well to demonstrate the solution and make it easier to understand the behavior.

- As for the solution itself, I think we may need to clarify our requirements here and update the description after confirming with the team. 

As @Skyge mentioned above, 
> I assume that 12,000 token will be distributed per day(suppose one day has 6646 blocks), then I just used two accounts to `stake`, `user1` staked at the beginning with 2,000 token, after 100 blocks, `user2` also staked with 2,000 token, then `user1` exited staking to get reward, and next `user2` also exited to get reward, I found that the rewards of the two users are almost equal.

To distribute the reward fairly, the global distribution rate should stay the same, which means the user with the same amount and staking period will get the same amount of reward regardless of the start time of its staking. Then based on the constant global distribution rate, a user with a longer staking period should get a larger weight, so the user's distribution rate is relatively faster than others. The original implementation only takes into account the staking amount.

Please keep up the good work, we are looking forward to more commits and discussions.

**Comment by Skyge** [comment]
@AaronZgl Hey, add my [test case](https://github.com/dforce-network/staking/blob/feature-test-bounty/test/testBounty.js), please have a check, here is the result: 

bounty test

You can find in the test case file, user1 and user2 staked the same amount, and user1 staked for a longer time, but user1 did not get more rewards.

**Comment by AaronZgl** [comment]
@Skyge Yes, I have found this problem. I am fixing it. I will update the repaired code as soon as possible.

**Comment by Skyge** [comment]
Okay, I will have a check now.

**Comment by AaronZgl** [comment]
@Skyge Hello, I have fixed the bug and updated code. you can test again.

**Comment by AaronZgl** [comment]
> Okay, I will have a check now.

Maybe you need to pay attention when you  test . I changed the name of the function：
unstake() -> withdraw()
withdraw() -> getReward()
balanceOf() -> rewards()
add exits()

**Comment by Skyge** [comment]
Thanks for your kind reminder, yeah, I am reviewing your changes now.

**Comment by Skyge** [comment]
@AaronZgl  Add a new test case for your commit, please have a check:

bounty-test

**Comment by AaronZgl** [comment]
> @AaronZgl Add a new test case for your commit, please have a check:
> 
> bounty-test

@Skyge  Yes, there is a restake bug. I ignored this situation. I have fixed it, you could test it again.

**Comment by AaronZgl** [comment]
@Skyge this is my latest test result:
testResult

**Comment by Skyge** [comment]
@AaronZgl Add a new test case for your commit, please have a check:
bounty-test

**Comment by AaronZgl** [comment]
@Skyge I have fixed the exit bug, please test it again.

**Comment by Skyge** [comment]
@AaronZgl Okay, but maybe later, cause I have got to finish my work today first, I will let you know if I finish the new test, thanks for your work!

**Comment by AaronZgl** [comment]
@AaronZgl  Okay, thank you.

**Comment by Skyge** [comment]
@AaronZgl Add a new test case for your commit, please have a check:
bounty-test

**Comment by AaronZgl** [comment]
@Skyge Resolved the error.

**Comment by Skyge** [comment]
@AaronZgl Add a new test case for your commit, please have a check:
bounty-test

**Comment by Skyge** [comment]
```
stake       -->> deposit to get reward
withdraw    -->> withdraw staked token
exit        -->> withdraw all staked token and get all rewards
getReward   -->> get some reward tokens and continue to stake
rewards     -->> query current reward amount
```
Hey, @joyious  if you have time, please have a check, just like what we discussed before, use two mappings to record: 
`userStakeAmount` and `userStakeBlock` for user staking details, 
`updateStakeAmount` and `updateBlocks` for total staking details. 
I am not sure for their distributing algorithms, need more test, but common functions almost finished.

**Comment by AaronZgl** [comment]
> @AaronZgl Add a new test case for your commit, please have a check:
> bounty-test

@Skyge This is an excepted error because the withdraw amount is 0. But it could be more friendly. I have updated the `exit `function and add error messages in `stake` and `withdraw` function.

**Comment by Skyge** [comment]
Good job! I will test it later!

**Comment by joyious** [comment]
Hey @AaronZgl! We are impressed by your progress, I think we are getting close!

For easy test integration I just created a pr AaronZgl/staking#1, please review the test cases and results and kindly merge it.

Meanwhile, I may need take a closer look in the solution itself. I will make some inline comments, hope you can help me to understand your code better.

Again, sorry for not being able to respond in time, thanks for your patience and good work!

**Comment by Skyge** [comment]
@joyious  Thanks for your work! and  @AaronZgl Add a new test case for your commit, please have a check:
bounty-test

Give a short description, user1 stakes 500 for 20 blocks, then mine another 20 blocks, user2 stakes 500 for another 20 blocks, generally speaking, stake the same amount for the same time, users should get the same rewards.

**Comment by Skyge** [comment]
Another case:
test-bounty

**Comment by AaronZgl** [comment]
> Hey @AaronZgl! We are impressed by your progress, I think we are getting close!
> 
> For easy test integration I just created a pr [AaronZgl#1](https://github.com/AaronZgl/staking/pull/1), please review the test cases and results and kindly merge it.
> 
> Meanwhile, I may need take a closer look in the solution itself. I will make some inline comments, hope you can help me to understand your code better.
> 
> Again, sorry for not being able to respond in time, thanks for your patience and good work!

@joyious Okay, I will review it carefully tonight.

**Comment by AaronZgl** [comment]
> @joyious Thanks for your work! and @AaronZgl Add a new test case for your commit, please have a check:
> bounty-test
> 
> Give a short description, user1 stakes 500 for 20 blocks, then mine another 20 blocks, user2 stakes 500 for another 20 blocks, generally speaking, stake the same amount for the same time, users should get the same rewards.

@Skyge The rewards per block is different. The higher the block height, the more rewards will be given. User2 got more rewards because he staked in higher 20 blocks.

**Comment by Skyge** [comment]
> The rewards per block is different. The higher the block height, the more rewards will be given. User2 got more rewards because he staked in higher 20 blocks.

Yeah, I will discuss with my leader later, and it appears that I misunderstood.

**Comment by AaronZgl** [comment]
@Skyge @joyious I'm sorry to get back to you so late. I have merged the pull request about test case. The third case failed  because of a bug that  I have fixed. The second case failed because the test logic is wrong.

as the issue described: The higher the block, the more rewards.
Sn represents the rewards in the nth block, R1n  represents the rewards of user1 in  nth block. There is the following expression:

1. S1 < S2 < S3 < ... < Sn
2. S1 + S2 + ... + Sn = totalRewards
3. R1n = stake amount of user1  in  nth block/ total stake amount in nth block

The rewards of user1 who staked from block 10 to block 30 should be less than the rewards of user2 who staked from block 40 to block 60.

**Pull request closed without merging**
